[platformio]
default_envs = fysetc_e4
src_dir = .
src_filter = +<*.ino> +<src/> -<OnStepX-Plugins/**/*> -<.OnStepX-Plugins/**/*>

[env:fysetc_e4]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
upload_speed = 921600
board_build.partitions = huge_app.csv

build_flags = 
    -D ONSTEPX
    -D CORE_DEBUG_LEVEL=0

lib_deps =
    plerup/EspSoftwareSerial